version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    platform: linux/amd64
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./configs/hadoop-hive.env
    ports:
      - "50070:50070"
    
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    platform: linux/amd64
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./configs/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    platform: linux/amd64
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./configs/hadoop-hive.env

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    platform: linux/amd64
    env_file:
      - ./configs/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    platform: linux/amd64
    env_file:
      - ./configs/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    platform: linux/amd64
    ports:
      - "5432:5432"

  huedb:
    image: postgres:12.1-alpine
    platform: linux/amd64
    volumes:
      - pg_data:/var/lib/postgresl/data/
    ports:
      - "5432"
    env_file:
      - ./configs/hadoop-hive.env
    environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083"
  
  hue:
    image: gethue/hue:4.6.0
    platform: linux/amd64
    environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083 huedb:5000"
    ports:
      - "8888:8888"
    volumes:
      - ./configs/hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
    links:
      - huedb

  superset:
    image: apache/superset:latest
    platform: linux/amd64
    depends_on:
      - hive-server
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "thisISaSECRET_1234"
      SQLALCHEMY_DATABASE_URI: "sqlite:////var/lib/superset/superset.db"
    ports:
      - "8088:8088"
    volumes:
      - superset:/var/lib/superset
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  namenode:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/namenode
  datanode:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/datanode
  pg_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/pg_data
  superset:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/superset
  hue:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/hue